#packages
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
library(tidyverse)
library(ggpubr)
library(rmapshaper)
library(janitor)
library(sqldf)
library(rgdal)
library(tidymodels)
library(stats)
library(DiagrammeR)

################################################################################################################

#Read csv
hkpop_csv <- read_csv("data/Population_districts_092020.CSV")
hkpop_csv <- clean_names(hkpop_csv)
#Sort by alphabetic order
hkpop_csv <- hkpop_csv[order(hkpop_csv$district_council_district),]

hkpopdensity <- read_csv("data/Population_density_revised.csv")
#Sort by alphabetic order
hkpopdensity <- hkpopdensity[order(hkpopdensity$District),]

#Read Hong Kong map
HKdistricts <- st_read(here::here("data","Hong_Kong_18_Districts-shp", "HKDistrict18.shp")) %>%
  st_transform(.,2326)
#Sort by alphabetic order
HKdistricts <- HKdistricts[order(HKdistricts$ENAME),]

################################################################################################################

###Descriptive statistics

##histogram
#population histogram
x <- hkpop_csv$both_sexes
h<-hist(x, breaks=10, col="white", xlab="Hong Kong Population",
   main="Histogram")
xfit<-seq(min(x),max(x),length=40)
yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
yfit <- yfit*diff(h$mids[1:2])*length(x)
lines(xfit, yfit, col="blue", lwd=3)

#2011 population density histogram
y <- hkpopdensity$'2011'
h2<-hist(y, breaks=10, col="white", xlab="Hong Kong Population Density",
   main="Histogram")
xfit<-seq(min(y),max(y),length=40)
yfit<-dnorm(xfit,mean=mean(y),sd=sd(y))
yfit <- yfit*diff(h2$mids[1:2])*length(y)
lines(xfit, yfit, col="blue", lwd=3)

#2016 population density histogram
z <- hkpopdensity$'2016'
h3<-hist(z, breaks=10, col="white", xlab="Hong Kong Population Density",
   main="Histogram")
xfit<-seq(min(z),max(z),length=40)
yfit<-dnorm(xfit,mean=mean(z),sd=sd(z))
yfit <- yfit*diff(h3$mids[1:2])*length(z)
lines(xfit, yfit, col="blue", lwd=3)

#clustering between income and population
eleven <- hkpopdensity$'2011'
sixteen <- hkpopdensity$'2016'
dfVar <-  data.frame(eleven, sixteen)

mydata <- dfVar %>%
dplyr::select(c(eleven, sixteen))

#scaling
mydata <- scale(mydata)
mydata <- data.frame(mydata)


histplot <- ggplot(data=mydata, aes(x=eleven))
histplot +geom_histogram(bins=15)

histplot <- ggplot(data=mydata, aes(x=sixteen))
histplot +geom_histogram(bins=10)

fit <- mydata %>%
kmeans(., 3, nstart=25)

centroid <- tidy(fit)%>%
print()%>%
dplyr::select(eleven, sixteen)

p <- ggplot(mydata,aes(eleven, sixteen))+
  geom_point(aes(colour=factor(fit$cluster)))+
  geom_point(data=centroid,aes(eleven, sixteen), size=7, shape=18)+ theme(legend.position="none")
  
HKdistricts <- fit %>% 
  # 
  augment(., HKdistricts)%>%
  dplyr::select(ENAME, .cluster)%>%
  #make sure the .cluster column is numeric
  mutate(across(.cluster, as.numeric))%>%
  # join the .cluster to our sf layer
  left_join(HKdistricts, 
            .,
            by = c("ENAME" = "ENAME"))


#now map our geodeomographic classification
map <- ggplot(HKdistricts) + 
  geom_sf(mapping = aes(fill=.cluster))+
  scale_fill_continuous(breaks=c(1,2,3))

map


################################################################################################################

###Population

#Adjusting population csv
HKpop <- hkpop_csv[,4] %>%
mutate(hkpop_csv[,1]) %>%
dplyr::rename(ENAME= 'district_council_district') %>%
mutate(hkpop_csv[,8]) %>%
mutate(hkpop_csv[,9])

#Change to SF
hkpop_sf1 = st_as_sf(HKpop, coords = c("latitude","longitude"), crs = 2326)

#Function
Joinfun <- function(data1, data2){

output<- data1%>%
  st_join(data2,.) 

  return(output)
}

Population <- Joinfun(hkpop_sf1, HKdistricts)

Population <-Population %>%
mutate('Population count' = hkpop_sf1$both_sexes)

tmap_mode("plot")

# set the breaks
# for our mapped data
breaks = c(100000, 200000, 300000, 400000, 500000, 600000, 700000) 

# plot map
tm1 <- tm_shape(Population) + 
  tm_polygons("Population count", 
              breaks=breaks,
              palette="BuGn", size=0.9)+
  tm_legend(show=TRUE, position=c("right","bottom"), text.size=0.9)+
  tm_layout(frame=FALSE)+
  tm_scale_bar(position=c("left", "top"))+
  tm_compass(north=0, position=c("left","top")
  )


################################################################################################################
#Public Open areas
hkdata_csv <- read_csv("data/HKGS_Dataset_Public-Open-Space_2020-01-23-1129-20_fullset.csv")
hkdata_csv <- clean_names(hkdata_csv)
hkdata_sf1 = st_as_sf(hkdata_csv, coords = c("easting_zuo_biao_dong","northing_zuo_biao_bei"), crs = 2326)

hkdata_sf1 <- distinct(hkdata_sf1)

HKpublicopenSub <- hkdata_sf1[HKdistricts,]
tmap_mode("view")
tm_shape(HKdistricts) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(HKpublicopenSub) +
  tm_dots(col = "blue")

window <- as.owin(HKdistricts)
plot(window)

#create a ppp object
HKpublicopenSub<- HKpublicopenSub %>%
as(., 'Spatial')

HKpublicopenSub.ppp <- ppp(x=HKpublicopenSub@coords[,1],
y= HKpublicopenSub@coords[,2],
window=window)

HKpublicopenSub.ppp %>%
plot(.,pch=16,cex=0.5,
main="Public open areas in Hong Kong")

#Kernel Density Esitmation
HKpublicopenSub.ppp %>%
density(., sigma=1000) %>%
plot()

################################################################################################################

##flowchart

DiagrammeR::grViz("digraph {

graph [layout = dot, rankdir = LR]

node [shape = rectangle, style = filled, fillcolor = Linen]

data1 [label = 'Population \n Observation']
data2 [label = 'Population Density \n Analysis']
spaces [label =  'Comparison \n with \n Public Open \n Spaces', shape = circle, fillcolor = Beige, fixedsize = true, width = 1.7]
cluster [label = 'Clustering \n Analysis']

data1  -> data2 -> cluster -> {spaces}
}")
